In [2]:
import pandas as pd

In [11]:
df_in = pd.read_csv('./data/upstream_weekly-field_annual_production_kbd_2015-2023.csv')
list(df_in.columns)

C:\Users\jake.stanger\AppData\Local\Temp\ipykernel_28120\3693390114.py:1: DtypeWarning: Columns (64,70,81,85,93,94,95,96,98,99,100,102,104,105,106,107,108,109,110,111,112,113,115,116,117,118,119,120,121,122,123,124,125,126) have mixed types. Specify dtype option on import or set low_memory=False.
  df_in = pd.read_csv('./data/upstream_weekly-field_annual_production_kbd_2015-2023.csv')

['id_field_metrics',
 'id_field',
 'field_name',
 'id_field_group',
 'field_group',
 'field_is_top_level',
 'field_is_discovery',
 'id_country',
 'country_name',
 'id_metric',
 'metric_name',
 'id_unit',
 'unit',
 'id_year',
 'year',
 'year_actual_forecast',
 'year_is_current',
 'id_produced_remaining',
 'produced_remaining',
 'id_commercial_technical',
 'commercial_technical',
 'commercial_technical_breakdown',
 'prms_commercial_subcommercial',
 'prms_breakdown',
 'id_product',
 'liquid_gas',
 'liquid_gas_breakdown',
 'id_category',
 'category',
 'category_breakdown',
 'id_price_deck',
 'price_deck',
 'price_deck_long_term_brent',
 'id_real_nominal',
 'real_nominal',
 'id_discount',
 'discount_rate',
 'metric_value',
 'metric_short_code',
 'metric_order',
 'id_theme',
 'unit_short_code',
 'unit_metric_imperial',
 'metric_is_volume',
 'metric_can_be_summed',
 'iso_3166_1_alpha_3_code',
 'id_super_region',
 'super_region',
 'id_region',
 'region',
 'id_sector',
 'sector_name',
 'sector_country',
 'country_region',
 'is_arctic',
 'country_opec_oecd',
 'onshore_offshore_tags',
 'water_depth_category_tags',
 'id_basin',
 'basin_name',
 'field_group_level',
 'field_is_parent',
 'id_field_parent',
 'field_parent',
 'field_production_area',
 'field_operator',
 'field_name_unique',
 'field_oil_gas',
 'field_hydrocarbon_type',
 'field_conventional_unconv',
 'field_unconventional_type',
 'field_onshore_offshore',
 'field_onshore_offshore_break',
 'field_primary_resource_theme',
 'field_primary_resource_group',
 'field_taxation',
 'field_fiscal_regime',
 'field_status',
 'field_prms_breakdown',
 'field_maturity',
 'field_development_type',
 'field_project_type',
 'field_is_lng_supply',
 'field_date_discovery',
 'field_year_discovery',
 'field_date_feed',
 'field_date_fid',
 'field_year_capex_first',
 'field_date_production_start',
 'field_year_production_start',
 'field_year_production_end',
 'field_size',
 'field_awarded_as_dro',
 'field_recovery_stage',
 'field_drive_mechanism_primary',
 'field_drive_mechanism_second',
 'field_drive_mechanism_tertiary',
 'field_class_oil_gravity',
 'field_class_oil_sulphur',
 'field_class_acid_gas',
 'field_class_sour_gas',
 'id_play',
 'play_name',
 'id_sub_play',
 'sub_play_name',
 'sub_play_name_short',
 'play_conventional_unconv',
 'play_resource_type_primary',
 'play_resource_type_all',
 'play_hydrocarbon_primary',
 'play_hydrocarbon_all',
 'play_development_status',
 'play_development_type',
 'play_well_slant',
 'play_model_type_well_only',
 'play_lithology_primary',
 'play_grade_environmental_reg',
 'play_grade_fiscal_terms',
 'play_grade_market_gas',
 'play_grade_price_gas',
 'play_grade_infrastructure',
 'play_grade_land_access',
 'play_grade_market_liq',
 'play_grade_resource_upside',
 'play_grade_supply_chain',
 'play_grade_technology_upside',
 'play_grade_water_access',
 'field_centroid_x',
 'field_centroid_y',
 'id_portal_area',
 'id_history']

In [16]:
df = df_in[['country_name','field_name','year','metric_value','unit']]
df = df[df['country_name']=='Azerbaijan']

x=1
if all(df['unit']=='kboe/d'):
    print('All values are in kboe/d \n Multiplying by 365...')
    x=365

All values are in kboe/d
 Multiplying by 365...

In [17]:
result = df.groupby('year')['metric_value'].sum() * x
out = result.reset_index()
out

   year   metric_value
0  2015  529242.430192
1  2016  523815.986580
2  2017  502711.579124
3  2018  527751.086036
4  2019  593839.341792
5  2020  590593.624844
6  2021  676856.889140
7  2022  684255.727636
8  2023  691141.120340

In [10]:
out.to_csv('./data/AZE_prod.csv',index=False)

In [ ]:
field_names = [
    'Absheron',
    
]

In [31]:
df[df['field_name'].str.contains('Bahar',case=False)]

      country_name       field_name  year  metric_value    unit
19045   Azerbaijan  Gum Deniz-Bahar  2015       1.26000  kboe/d
19046   Azerbaijan  Gum Deniz-Bahar  2015       0.00000  kboe/d
19047   Azerbaijan  Gum Deniz-Bahar  2015       0.12000  kboe/d
19048   Azerbaijan  Gum Deniz-Bahar  2015       3.22080  kboe/d
19049   Azerbaijan  Gum Deniz-Bahar  2016       0.89000  kboe/d
...            ...              ...   ...           ...     ...
19112   Azerbaijan            Bahar  2022       3.81920  kboe/d
19113   Azerbaijan            Bahar  2023       0.00000  kboe/d
19114   Azerbaijan            Bahar  2023       0.00000  kboe/d
19115   Azerbaijan            Bahar  2023       0.03000  kboe/d
19116   Azerbaijan            Bahar  2023       4.41232  kboe/d

[72 rows x 5 columns]

In [23]:
df[df['field_name']=='Absheron']

       country_name field_name  year  metric_value    unit
256665   Azerbaijan   Absheron  2015       0.40000  kboe/d
256666   Azerbaijan   Absheron  2015       0.00000  kboe/d
256667   Azerbaijan   Absheron  2015       0.00000  kboe/d
256668   Azerbaijan   Absheron  2015       0.05632  kboe/d
256669   Azerbaijan   Absheron  2016       1.16000  kboe/d
256670   Azerbaijan   Absheron  2016       0.00000  kboe/d
256671   Azerbaijan   Absheron  2016       0.00000  kboe/d
256672   Azerbaijan   Absheron  2016       0.11968  kboe/d
256673   Azerbaijan   Absheron  2017       1.92000  kboe/d
256674   Azerbaijan   Absheron  2017       0.00000  kboe/d
256675   Azerbaijan   Absheron  2017       0.00000  kboe/d
256676   Azerbaijan   Absheron  2017       0.19888  kboe/d
256677   Azerbaijan   Absheron  2018       2.32000  kboe/d
256678   Azerbaijan   Absheron  2018       0.00000  kboe/d
256679   Azerbaijan   Absheron  2018       0.00000  kboe/d
256680   Azerbaijan   Absheron  2018       0.23936  kboe/d
256681   Azerbaijan   Absheron  2019       3.23000  kboe/d
256682   Azerbaijan   Absheron  2019       0.00000  kboe/d
256683   Azerbaijan   Absheron  2019       0.00000  kboe/d
256684   Azerbaijan   Absheron  2019       0.33440  kboe/d
256685   Azerbaijan   Absheron  2020       3.23000  kboe/d
256686   Azerbaijan   Absheron  2020       0.00000  kboe/d
256687   Azerbaijan   Absheron  2020       0.00000  kboe/d
256688   Azerbaijan   Absheron  2020       0.33440  kboe/d
256689   Azerbaijan   Absheron  2021       3.31000  kboe/d
256690   Azerbaijan   Absheron  2021       0.00000  kboe/d
256691   Azerbaijan   Absheron  2021       0.00000  kboe/d
256692   Azerbaijan   Absheron  2021       0.34144  kboe/d
256693   Azerbaijan   Absheron  2022       3.39000  kboe/d
256694   Azerbaijan   Absheron  2022       0.00000  kboe/d
256695   Azerbaijan   Absheron  2022       0.00000  kboe/d
256696   Azerbaijan   Absheron  2022       0.35024  kboe/d
256697   Azerbaijan   Absheron  2023       3.56000  kboe/d
256698   Azerbaijan   Absheron  2023       0.00000  kboe/d
256699   Azerbaijan   Absheron  2023       0.00000  kboe/d
256700   Azerbaijan   Absheron  2023       0.36784  kboe/d